apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
        - name: nginx-proxy
          image: yaroslavkostyannikov/nginx:v0.1.0
          imagePullPolicy: "IfNotPresent"
          ports:
          - containerPort: 443
            name: nginx-proxy
            protocol: TCP
