apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: applications
  labels:
    app: nginx-proxy
spec:
  type: LoadBalancer
  ports:
   - port: 443
     protocol: TCP
     targetPort: 443
  selector:
   app: nginx-proxy
