apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-ui
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger-ui
  template:
    metadata:
      labels:
        app: swagger-ui
    spec:
      containers:
        - name: swagger-ui
          image: yaroslavkostyannikov/swagger:v0.0.1
          imagePullPolicy: "IfNotPresent"
          env:
          - name: SWAGGER_JSON
            value: "/foo/swagger.yml"
          ports:
          - containerPort: 8080
            name: swagger-ui
            protocol: TCP
      restartPolicy: Always
