apiVersion: v1
kind: Service
metadata:
  name: swagger-ui
  namespace: applications
  labels:
    app: swagger-ui
spec:
  type: ClusterIP
  ports:
   - port: 8080
     protocol: TCP
     targetPort: 8080
  selector:
   app: swagger-ui
