name: Tests - booking-server application

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.3

    - name: Build
      run: go build -o booking-server cmd/booking-server/main.go

    - name: Test
      run: go test -tags=test -v ./...
